# Generated by Django 5.1.1 on 2026-02-06 07:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], default='Company', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_email', models.EmailField(max_length=254)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('point_of_presence', models.CharField(blank=True, default='', help_text='Point of Presence locations (comma-separated)', max_length=200)),
                ('has_adc_services', models.BooleanField(default=False, help_text='Has services in ADC data center')),
                ('has_icolo_services', models.BooleanField(default=False, help_text='Has services in Icolo data center')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_client_name_76d9ae_idx'), models.Index(fields=['primary_email'], name='core_client_primary_b226d1_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'primary_email'), name='unique_client_name_email')],
            },
        ),
    ]
