# Generated by Django 5.1.1 on 2026-02-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_2fa_required",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user must enable 2FA before accessing the system.",
            ),
        ),
    ]
