# Generated by Django 5.1.1 on 2026-03-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_2fa_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('cloud_support_engineer', 'Cloud Support Engineer'), ('infra_engineer', 'Infrastructure Engineer'), ('service_delivery_engineer', 'Service Delivery Engineer'), ('account_manager', 'Account Manager'), ('sales_admin', 'Sales Admin')], default='cloud_support_engineer', help_text='Role of the user in the system.', max_length=32),
        ),
    ]
