# Generated by Django 5.1.1 on 2026-02-06 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SDWAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('provider', models.CharField(choices=[('Safaricom', 'Safaricom'), ('Liquid Telecom', 'Liquid Telecom'), ('Telkom', 'Telkom'), ('MTN', 'MTN'), ('Other', 'Other')], max_length=50, verbose_name='Provider')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdwan_records', to='core.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdwan_created_records', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdwan_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'SD-WAN',
                'verbose_name_plural': 'SD-WAN Records',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['account_number'], name='sdwan_sdwan_account_ce87f0_idx'), models.Index(fields=['provider'], name='sdwan_sdwan_provide_0c60b0_idx')],
                'constraints': [models.UniqueConstraint(fields=('client', 'account_number'), name='unique_client_account_number')],
            },
        ),
    ]
