# Generated by Django 5.1.1 on 2026-03-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan', '0002_enforce_unique_client_account_number_ci'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sdwan',
            name='unique_client_account_number_ci',
        ),
        migrations.RemoveIndex(
            model_name='sdwan',
            name='sdwan_sdwan_account_ce87f0_idx',
        ),
        migrations.RemoveField(
            model_name='sdwan',
            name='account_number',
        ),
    ]
