# Generated by Django 5.1.1 on 2026-03-10 07:21

from django.db import migrations, models


def copy_provider_to_providers(apps, schema_editor):
    SDWAN = apps.get_model('sdwan', 'SDWAN')
    for record in SDWAN.objects.all().only('id', 'provider'):
        provider = getattr(record, 'provider', None)
        record.providers = [provider] if provider else []
        record.save(update_fields=['providers'])


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan', '0003_remove_sdwan_unique_client_account_number_ci_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sdwan',
            name='sdwan_sdwan_provide_0c60b0_idx',
        ),
        migrations.AddField(
            model_name='sdwan',
            name='providers',
            field=models.JSONField(default=list, help_text='Select one or more providers', verbose_name='Providers'),
        ),
        migrations.RunPython(copy_provider_to_providers, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sdwan',
            name='provider',
        ),
    ]
