# Generated by Django 5.1.1 on 2026-02-06 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VeeamJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('site', models.CharField(choices=[('Angani ADC', 'Angani ADC'), ('Angani Icolo', 'Angani Icolo')], max_length=50, verbose_name='Site')),
                ('computer_name', models.CharField(max_length=100, verbose_name='Computer Name')),
                ('tag', models.CharField(blank=True, default='Not set', max_length=100, verbose_name='Tag')),
                ('os', models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows')], max_length=20, verbose_name='Operating System')),
                ('managed_by', models.CharField(choices=[('Backup Agent', 'Backup Agent'), ('VBR', 'VBR')], max_length=20, verbose_name='Managed By')),
                ('job_status', models.CharField(choices=[('Running', 'Running'), ('Success', 'Success'), ('Failed', 'Failed')], default='Running', max_length=20, verbose_name='Job Status')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veeam_records', to='core.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veeam_created_records', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veeam_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Veeam Job',
                'verbose_name_plural': 'Veeam Jobs',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['computer_name'], name='veeam_veeam_compute_65cbe0_idx'), models.Index(fields=['site'], name='veeam_veeam_site_1d6c10_idx'), models.Index(fields=['os'], name='veeam_veeam_os_aa15f1_idx'), models.Index(fields=['managed_by'], name='veeam_veeam_managed_7afa23_idx'), models.Index(fields=['job_status'], name='veeam_veeam_job_sta_81a38a_idx')],
                'constraints': [models.UniqueConstraint(fields=('client', 'computer_name'), name='unique_client_computer_ci')],
            },
        ),
    ]
