# Generated by Django 5.1.1 on 2026-02-25 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_rename_pop_icolo_mba'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeCX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sip_provider', models.CharField(choices=[('Angani', 'Angani'), ('Safaricom', 'Safaricom'), ('Airtel', 'Airtel')], default='Angani', max_length=20)),
                ('fqdn', models.CharField(max_length=100, unique=True)),
                ('license_type', models.CharField(choices=[('3CX Pro', '3CX Pro'), ('3CX Enterprise', '3CX Enterprise')], max_length=20)),
                ('simultaneous_calls', models.IntegerField(choices=[(4, '4 SC'), (8, '8 SC'), (16, '16 SC'), (24, '24 SC'), (32, '32 SC'), (48, '48 SC'), (64, '64 SC'), (96, '96 SC'), (128, '128 SC'), (256, '256 SC')], default=4)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threecx_records', to='core.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threecx_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threecx_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['fqdn'], name='threecx_thr_fqdn_fbaccc_idx'), models.Index(fields=['sip_provider'], name='threecx_thr_sip_pro_c1967d_idx'), models.Index(fields=['license_type'], name='threecx_thr_license_40588b_idx')],
            },
        ),
    ]
