# Generated by Django 5.1.1 on 2026-03-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threecx', '0003_remove_unique_threecx_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threecx',
            name='license_type',
            field=models.CharField(choices=[('3CX Basic', '3CX Basic'), ('3CX Pro', '3CX Pro'), ('3CX Enterprise', '3CX Enterprise')], max_length=20),
        ),
        migrations.AlterField(
            model_name='threecx',
            name='simultaneous_calls',
            field=models.IntegerField(choices=[(1, '1 SC'), (2, '2 SC'), (4, '4 SC'), (8, '8 SC'), (16, '16 SC'), (24, '24 SC'), (32, '32 SC'), (48, '48 SC'), (64, '64 SC'), (96, '96 SC'), (128, '128 SC'), (256, '256 SC')], default=4),
        ),
        migrations.AlterField(
            model_name='threecx',
            name='sip_provider',
            field=models.CharField(choices=[('None', 'None'), ('Angani', 'Angani'), ('Safaricom', 'Safaricom'), ('Airtel', 'Airtel'), ('JTL', 'JTL')], default='None', max_length=20),
        ),
    ]
