# Generated by Django 5.1.1 on 2026-03-10 07:53

import threecx.models
from django.db import migrations, models


def copy_sip_provider_to_list(apps, schema_editor):
    ThreeCX = apps.get_model("threecx", "ThreeCX")
    for record in ThreeCX.objects.all().only("id", "sip_provider"):
        provider = getattr(record, "sip_provider", None)
        record.sip_providers = [provider] if provider else []
        record.save(update_fields=["sip_providers"])


def restore_single_sip_provider(apps, schema_editor):
    ThreeCX = apps.get_model("threecx", "ThreeCX")
    for record in ThreeCX.objects.all().only("id", "sip_providers"):
        providers = record.sip_providers or []
        record.sip_provider = providers[0] if providers else "None"
        record.save(update_fields=["sip_provider"])


class Migration(migrations.Migration):

    dependencies = [
        ('threecx', '0004_alter_threecx_license_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='threecx',
            name='threecx_thr_sip_pro_c1967d_idx',
        ),
        migrations.AddField(
            model_name='threecx',
            name='sip_providers',
            field=models.JSONField(default=threecx.models.default_sip_provider_list, help_text='Select one or more SIP providers', verbose_name='SIP Providers'),
        ),
        migrations.RunPython(copy_sip_provider_to_list, restore_single_sip_provider),
        migrations.RemoveField(
            model_name='threecx',
            name='sip_provider',
        ),
    ]
