# Generated by Django 5.1.1 on 2026-02-06 07:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('service_description', models.TextField()),
                ('date_of_request', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('date_of_completion', models.DateTimeField(blank=True, null=True)),
                ('job_completion_certificate', models.CharField(choices=[('Shared', 'Shared'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('engineer', models.ForeignKey(limit_choices_to={'groups__name': 'Engineers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-date_of_request'],
                'indexes': [models.Index(fields=['status'], name='pm_project_status_d6f81d_idx'), models.Index(fields=['customer_name'], name='pm_project_custome_4450c5_idx')],
            },
        ),
    ]
