# Generated by Django 5.1.1 on 2026-02-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_project_special_notes_project_provisioning_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='provisioning_form',
        ),
        migrations.RemoveField(
            model_name='project',
            name='special_notes',
        ),
    ]
